[package]
name = "flame-clustering"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derivative = "2.2.0"
num-traits = "0.2"

[dev-dependencies]
